-- begin PLSTP_COMPANY
create unique index IDX_PLSTP_COMPANY_UK_CODE on PLSTP_COMPANY (CODE) where DELETE_TS is null ^
-- end PLSTP_COMPANY
-- begin PLSTP_EMPLOYEE
alter table PLSTP_EMPLOYEE add constraint FK_PLSTP_EMPLOYEE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table PLSTP_EMPLOYEE add constraint FK_PLSTP_EMPLOYEE_ON_MANAGER foreign key (MANAGER_ID) references PLSTP_EMPLOYEE(ID)^
create unique index IDX_PLSTP_EMPLOYEE_UK_EMAIL on PLSTP_EMPLOYEE (EMAIL) where DELETE_TS is null ^
create index IDX_PLSTP_EMPLOYEE_ON_USER on PLSTP_EMPLOYEE (USER_ID)^
create index IDX_PLSTP_EMPLOYEE_ON_MANAGER on PLSTP_EMPLOYEE (MANAGER_ID)^
-- end PLSTP_EMPLOYEE
-- begin PROJECTS_COMPANIES_LINK
alter table PROJECTS_COMPANIES_LINK add constraint FK_PROCOM_ON_PROJECT foreign key (PROJECT_ID) references PLSTP_PROJECT(ID)^
alter table PROJECTS_COMPANIES_LINK add constraint FK_PROCOM_ON_COMPANY foreign key (COMPANY_ID) references PLSTP_COMPANY(ID)^
-- end PROJECTS_COMPANIES_LINK
